# named list of all robots
robots:
  cf1:
    enabled: true
    uri: radio://0/1/250K/E7E7E7E7E7
    initial_position: [1.2, 1.8, 0.02]
    type: cf21    # see robot_types
    firmware_params:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: false
      custom_topics:
        topic_name3:
          frequency: 30
          vars: [acc.x, acc.y, acc.z, gyro.x, gyro.y, gyro.z]
  cf42:
    enabled: false
    uri: radio://0/42/250K/E7E7E7E7E7
    initial_position: [1.2, 0.0, 0.02]
    type: cf21    # see robot_types
    firmware_params:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: true
      custom_topics:
        topic_name3:
          frequency: 30
          vars: [acc.x, acc.y, acc.z, gyro.x, gyro.y, gyro.z]
  cf3:
    enabled: false
    uri: radio://0/3/250K/E7E7E7E7E7
    initial_position: [-1.2, 1.8, 0.02]
    type: cf21    # see robot_types
    firmware_params:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: false
      custom_topics:
        topic_name3:
          frequency: 30
          vars: [acc.x, acc.y, acc.z, gyro.x, gyro.y, gyro.z]

  cf4:
    enabled: false
    uri: radio://0/4/250K/E7E7E7E7E7
    initial_position: [-1.2, 0.03, 0.02]
    type: cf21_mocap_deck    # see robot_types
    firmware_params:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: false
      custom_topics:
        topic_name3:
          frequency: 30
          vars: [acc.x, acc.y, acc.z, gyro.x, gyro.y, gyro.z]
  cf5:
    enabled: false
    uri: radio://0/5/250K/E7E7E7E7E7
    initial_position: [-1.2, 0.03, 0.02]
    type: cf21_mocap_deck    # see robot_types
    firmware_params:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: false
      custom_topics:
        topic_name3:
          frequency: 30
          vars: [acc.x, acc.y, acc.z, gyro.x, gyro.y, gyro.z]
  cf6:
    enabled: false
    uri: radio://0/6/250K/E7E7E7E7E7
    initial_position: [0.6, 0.6, 0.02]
    type: cf21_mocap_deck    # see robot_types
    firmware_params:
      kalman:
        pNAcc_xy: 1.0 # default 0.5
    firmware_logging:
      enabled: false
      custom_topics:
        topic_name3:
          frequency: 30
          vars: [acc.x, acc.y, acc.z, gyro.x, gyro.y, gyro.z]
# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #   enabled: true
    #   default_topics:
    #   pose:
    #     frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]

  cf21_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: false
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 30 # Hz
    custom_topics:
      topic_name1:
        frequency: 30 # Hz
       # vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.z", "stateEstimateZ.roll", "stateEstimateZ.pitch", "stateEstimateZ.yaw"]
        vars: [stateEstimate.x, stateEstimate.y, stateEstimate.z]
    #  topic_name2:
    #    frequency: 1 # Hz
    #    vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
